// Code generated by gen_sys_cmd_autogen.go, DO NOT EDIT.
package main

import (
	"gmicro/pkg/autocmd"
	"gmicro/service/dbproxy"
	"gmicro/service/dbproxyserver/impl"
)

var cmdList = []*autocmd.Cmd{

	{Server: dbproxy.ServerName, Path: dbproxy.GetModelListCMDPath, GRpcFunc: impl.GetModelList, OptionMap: map[string]string{}},
	{Server: dbproxy.ServerName, Path: dbproxy.InsertModelCMDPath, GRpcFunc: impl.InsertModel, OptionMap: map[string]string{}},
	{Server: dbproxy.ServerName, Path: dbproxy.DelModelCMDPath, GRpcFunc: impl.DelModel, OptionMap: map[string]string{}},
	{Server: dbproxy.ServerName, Path: dbproxy.UpdateModelCMDPath, GRpcFunc: impl.UpdateModel, OptionMap: map[string]string{}},
	{Server: dbproxy.ServerName, Path: dbproxy.BatchInsertModelCMDPath, GRpcFunc: impl.BatchInsertModel, OptionMap: map[string]string{}},
	{Server: dbproxy.ServerName, Path: dbproxy.SetModelCMDPath, GRpcFunc: impl.SetModel, OptionMap: map[string]string{}},
}
