// Code generated by gen_sys_cmd_autogen.go, DO NOT EDIT.

package main

import (
	"gmicro/pkg/autocmd"
	"gmicro/service/dbproxyserver/impl"
)

var cmdList = []*autocmd.Cmd{
	{Server: "dbproxyserver", Path: "/dbproxy/InsertModel", GRpcFunc: impl.InsertModel, OptionMap: map[string]string{"ApiMethod": "POST", "AuthType": "system"}},
	{Server: "dbproxyserver", Path: "/dbproxy/DelModel", GRpcFunc: impl.DelModel, OptionMap: map[string]string{"ApiMethod": "POST", "AuthType": "system"}},
	{Server: "dbproxyserver", Path: "/dbproxy/UpdateModel", GRpcFunc: impl.UpdateModel, OptionMap: map[string]string{"ApiMethod": "POST", "AuthType": "system"}},
	{Server: "dbproxyserver", Path: "/dbproxy/BatchInsertModel", GRpcFunc: impl.BatchInsertModel, OptionMap: map[string]string{"ApiMethod": "POST", "AuthType": "system"}},
	{Server: "dbproxyserver", Path: "/dbproxy/SetModel", GRpcFunc: impl.SetModel, OptionMap: map[string]string{"ApiMethod": "POST", "AuthType": "system"}},
	{Server: "dbproxyserver", Path: "/dbproxy/GetModelList", GRpcFunc: impl.GetModelList, OptionMap: map[string]string{"ApiMethod": "POST", "AuthType": "system"}},
}
