// Code generated by gen_sys_cmd_autogen.go, DO NOT EDIT.

package main

import (
	"gmicro/pkg/autocmd"
	"gmicro/service/dbproxyserver/impl"
)

var cmdList = []*autocmd.Cmd{
	{Server: "dbproxyserver", Path: "/dbproxyserver/InsertModel", GRpcFunc: impl.InsertModel, OptionMap: map[string]string{"ApiMethod": "POST"}},
	{Server: "dbproxyserver", Path: "/dbproxyserver/DelModel", GRpcFunc: impl.DelModel, OptionMap: map[string]string{"ApiMethod": "POST"}},
	{Server: "dbproxyserver", Path: "/dbproxyserver/UpdateModel", GRpcFunc: impl.UpdateModel, OptionMap: map[string]string{"ApiMethod": "POST"}},
	{Server: "dbproxyserver", Path: "/dbproxyserver/BatchInsertModel", GRpcFunc: impl.BatchInsertModel, OptionMap: map[string]string{"ApiMethod": "POST"}},
	{Server: "dbproxyserver", Path: "/dbproxyserver/SetModel", GRpcFunc: impl.SetModel, OptionMap: map[string]string{"ApiMethod": "POST"}},
	{Server: "dbproxyserver", Path: "/dbproxyserver/GetModelList", GRpcFunc: impl.GetModelList, OptionMap: map[string]string{"ApiMethod": "POST"}},
}
