// Code generated by cmd_path_autogen.go, DO NOT EDIT.
package dbproxy

const (
	GetModelListCMDPath     = "/dbproxy/GetModelList/"
	InsertModelCMDPath      = "/dbproxy/InsertModel/"
	DelModelCMDPath         = "/dbproxy/DelModel/"
	UpdateModelCMDPath      = "/dbproxy/UpdateModel/"
	BatchInsertModelCMDPath = "/dbproxy/BatchInsertModel/"
	SetModelCMDPath         = "/dbproxy/SetModel/"
)
