// Code generated by table_name_autogen.go, DO NOT EDIT.
package {{.ProtoName}}

import (
	"gmicro/pkg/gerr"
	"gmicro/pkg/rpc"
	"gmicro/pkg/uctx"
	"net/http"
)

{{ range .Items }}
func {{.RpcName}}(ctx uctx.IUCtx, req *{{.RpcName}}Req) (*{{.RpcName}}Rsp, error) {
	var resp {{.RpcName}}Rsp
	err := rpc.DoRequest(ctx, ServerName, {{.RpcName}}CMDPath, http.MethodPost, req, &resp)
	if err != nil {
		return nil, gerr.Wrap(err)
	}
	return &resp, nil
}
{{ end }}

