// Code generated by err_code_autogen.go, DO NOT EDIT.
package {{.ProtoName}}

import "gmicro/pkg/gerr"

const ServerName = "{{.ProtoName}}"

const ({{ range .Items }}
{{.Name}} int32 = {{.Value}}{{ end }}
)

var errCodeMsgMap = map[int32]string{
{{ range .Items }}
{{.Name}}:"{{.Comment}}",{{ end }}
}

func init() {
	gerr.RegisterErrCodeMsg(errCodeMsgMap)
}
