// Code generated by gen_sys_cmd_autogen.go, DO NOT EDIT.
package main

import (
	"gmicro/pkg/autocmd"
	"gmicro/service/{{.ProtoBase.ProtoName}}"
	"gmicro/service/{{.ProtoBase.ProtoName}}server/impl"
)

var cmdList = []*autocmd.Cmd{
{{ range .Items }}
	{Server: {{.ProtoName}}.ServerName, Path: {{.ProtoName}}.{{.RpcName}}CMDPath, GRpcFunc: impl.{{.RpcName}}, OptionMap: map[string]string{}},{{ end }}
}
